//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BuisResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuisResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.BuisResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Opening Date.
        /// </summary>
        internal static string AccountOpeningDate {
            get {
                return ResourceManager.GetString("AccountOpeningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string AccountsInfo {
            get {
                return ResourceManager.GetString("AccountsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        internal static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Type.
        /// </summary>
        internal static string ActivityType {
            get {
                return ResourceManager.GetString("ActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Amount of the Account.
        /// </summary>
        internal static string ActualAccountAmount {
            get {
                return ResourceManager.GetString("ActualAccountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Investment.
        /// </summary>
        internal static string ActualInvestment {
            get {
                return ResourceManager.GetString("ActualInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to List.
        /// </summary>
        internal static string AddToList {
            get {
                return ResourceManager.GetString("AddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Amount.
        /// </summary>
        internal static string ApprovedAmount {
            get {
                return ResourceManager.GetString("ApprovedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Loan Type.
        /// </summary>
        internal static string ApprovedLoanType {
            get {
                return ResourceManager.GetString("ApprovedLoanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Status.
        /// </summary>
        internal static string ApprovedStatus {
            get {
                return ResourceManager.GetString("ApprovedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximate Value of the Day.
        /// </summary>
        internal static string ApproximateValue {
            get {
                return ResourceManager.GetString("ApproximateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Amount of Asset.
        /// </summary>
        internal static string AssetAmount {
            get {
                return ResourceManager.GetString("AssetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        internal static string AssetInfo {
            get {
                return ResourceManager.GetString("AssetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Title.
        /// </summary>
        internal static string AssetName {
            get {
                return ResourceManager.GetString("AssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral Type 1 Percentage.
        /// </summary>
        internal static string Assurance1 {
            get {
                return ResourceManager.GetString("Assurance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral Type 2 Percentage.
        /// </summary>
        internal static string Assurance2 {
            get {
                return ResourceManager.GetString("Assurance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Statment.
        /// </summary>
        internal static string BalanceStatment {
            get {
                return ResourceManager.GetString("BalanceStatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Accounts.
        /// </summary>
        internal static string BankAccounts {
            get {
                return ResourceManager.GetString("BankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate in the table your accounts information.
        /// </summary>
        internal static string BankAccountsTitle {
            get {
                return ResourceManager.GetString("BankAccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Institution Name.
        /// </summary>
        internal static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board of Directors.
        /// </summary>
        internal static string BoardDirectors {
            get {
                return ResourceManager.GetString("BoardDirectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bourse Member.
        /// </summary>
        internal static string BourseMember {
            get {
                return ResourceManager.GetString("BourseMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code.
        /// </summary>
        internal static string BranchCode {
            get {
                return ResourceManager.GetString("BranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Branch.
        /// </summary>
        internal static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Site.
        /// </summary>
        internal static string BuildingSite {
            get {
                return ResourceManager.GetString("BuildingSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of data mining model used for scoring buisness.
        /// </summary>
        internal static string BuisModelDM {
            get {
                return ResourceManager.GetString("BuisModelDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of judgmental model used for ranking buisness.
        /// </summary>
        internal static string BuisModelJG {
            get {
                return ResourceManager.GetString("BuisModelJG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate ID.
        /// </summary>
        internal static string BuisnessID {
            get {
                return ResourceManager.GetString("BuisnessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        internal static string BuisnessRegistration {
            get {
                return ResourceManager.GetString("BuisnessRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Case.
        /// </summary>
        internal static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centeral Bureau.
        /// </summary>
        internal static string CenterBureau {
            get {
                return ResourceManager.GetString("CenterBureau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Bureau Information.
        /// </summary>
        internal static string CentralBureau {
            get {
                return ResourceManager.GetString("CentralBureau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string ChildNumber {
            get {
                return ResourceManager.GetString("ChildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children Health Status.
        /// </summary>
        internal static string ChildrenHealthStatus {
            get {
                return ResourceManager.GetString("ChildrenHealthStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral Amount.
        /// </summary>
        internal static string CollateralAmount {
            get {
                return ResourceManager.GetString("CollateralAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral Information.
        /// </summary>
        internal static string CollateralInformation {
            get {
                return ResourceManager.GetString("CollateralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral Type.
        /// </summary>
        internal static string CollateralType {
            get {
                return ResourceManager.GetString("CollateralType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conjoint Information.
        /// </summary>
        internal static string ConjointInformation {
            get {
                return ResourceManager.GetString("ConjointInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        internal static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To score corporates add them to the table.
        /// </summary>
        internal static string CorpAssessMsg {
            get {
                return ResourceManager.GetString("CorpAssessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        internal static string Corporate {
            get {
                return ResourceManager.GetString("Corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Main Activity.
        /// </summary>
        internal static string CorporateActivity {
            get {
                return ResourceManager.GetString("CorporateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Corporate Information.
        /// </summary>
        internal static string CorporateInformation {
            get {
                return ResourceManager.GetString("CorporateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Name.
        /// </summary>
        internal static string CorporateName {
            get {
                return ResourceManager.GetString("CorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Type.
        /// </summary>
        internal static string CorporateType {
            get {
                return ResourceManager.GetString("CorporateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Amount.
        /// </summary>
        internal static string CostAmount {
            get {
                return ResourceManager.GetString("CostAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string CostInfo {
            get {
                return ResourceManager.GetString("CostInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costs.
        /// </summary>
        internal static string Costs {
            get {
                return ResourceManager.GetString("Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate in the table your costs .
        /// </summary>
        internal static string CostsTitle {
            get {
                return ResourceManager.GetString("CostsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Type.
        /// </summary>
        internal static string CostType {
            get {
                return ResourceManager.GetString("CostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateInformation {
            get {
                return ResourceManager.GetString("CreateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Information.
        /// </summary>
        internal static string CreditInformation {
            get {
                return ResourceManager.GetString("CreditInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Credit Turn Over.
        /// </summary>
        internal static string CreditTurnOver {
            get {
                return ResourceManager.GetString("CreditTurnOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Guaranties.
        /// </summary>
        internal static string CurrentGuaranties {
            get {
                return ResourceManager.GetString("CurrentGuaranties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate the state of your guaranties.
        /// </summary>
        internal static string CurrentGuarantiesTitle {
            get {
                return ResourceManager.GetString("CurrentGuarantiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Group.
        /// </summary>
        internal static string CustomerGroup {
            get {
                return ResourceManager.GetString("CustomerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        internal static string CustomerInfo {
            get {
                return ResourceManager.GetString("CustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Number.
        /// </summary>
        internal static string CustomerNumber {
            get {
                return ResourceManager.GetString("CustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers History.
        /// </summary>
        internal static string CustomersHistory {
            get {
                return ResourceManager.GetString("CustomersHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        internal static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Insert Command.
        /// </summary>
        internal static string DBInsert {
            get {
                return ResourceManager.GetString("DBInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from List.
        /// </summary>
        internal static string DeleteFromList {
            get {
                return ResourceManager.GetString("DeleteFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependants.
        /// </summary>
        internal static string Dependants {
            get {
                return ResourceManager.GetString("Dependants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earnings.
        /// </summary>
        internal static string Earnings {
            get {
                return ResourceManager.GetString("Earnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economic Sector.
        /// </summary>
        internal static string EconomicSector {
            get {
                return ResourceManager.GetString("EconomicSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Information.
        /// </summary>
        internal static string EditInformation {
            get {
                return ResourceManager.GetString("EditInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Degree.
        /// </summary>
        internal static string EducationDegree {
            get {
                return ResourceManager.GetString("EducationDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Field.
        /// </summary>
        internal static string EducationField {
            get {
                return ResourceManager.GetString("EducationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education &amp; Job Information.
        /// </summary>
        internal static string EducationJobInformation {
            get {
                return ResourceManager.GetString("EducationJobInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the value of this field :.
        /// </summary>
        internal static string EnterValue {
            get {
                return ResourceManager.GetString("EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment Date.
        /// </summary>
        internal static string EstablishmentDate {
            get {
                return ResourceManager.GetString("EstablishmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities Information.
        /// </summary>
        internal static string FacilitiesInformation {
            get {
                return ResourceManager.GetString("FacilitiesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        internal static string FacilityInfo {
            get {
                return ResourceManager.GetString("FacilityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Type.
        /// </summary>
        internal static string FacilityType {
            get {
                return ResourceManager.GetString("FacilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        internal static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory / Workshop Information.
        /// </summary>
        internal static string FactoryWorkshop {
            get {
                return ResourceManager.GetString("FactoryWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fame.
        /// </summary>
        internal static string Fame {
            get {
                return ResourceManager.GetString("Fame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name.
        /// </summary>
        internal static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fox.
        /// </summary>
        internal static string FoxNumber {
            get {
                return ResourceManager.GetString("FoxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click To See the Details.
        /// </summary>
        internal static string GoToLoan {
            get {
                return ResourceManager.GetString("GoToLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guaranties.
        /// </summary>
        internal static string GuarantyInfo {
            get {
                return ResourceManager.GetString("GuarantyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Job or More.
        /// </summary>
        internal static string HasMoreJob {
            get {
                return ResourceManager.GetString("HasMoreJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Record.
        /// </summary>
        internal static string HealthInformation {
            get {
                return ResourceManager.GetString("HealthInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Status.
        /// </summary>
        internal static string HealthStatus {
            get {
                return ResourceManager.GetString("HealthStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing.
        /// </summary>
        internal static string Housing {
            get {
                return ResourceManager.GetString("Housing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification ID.
        /// </summary>
        internal static string IdentificationID {
            get {
                return ResourceManager.GetString("IdentificationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Exchange.
        /// </summary>
        internal static string InBourse {
            get {
                return ResourceManager.GetString("InBourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Amount.
        /// </summary>
        internal static string IncomeAmount {
            get {
                return ResourceManager.GetString("IncomeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string IncomeInfo {
            get {
                return ResourceManager.GetString("IncomeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Statement.
        /// </summary>
        internal static string IncomeStatement {
            get {
                return ResourceManager.GetString("IncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate in the table your incomes.
        /// </summary>
        internal static string IncomeTitle {
            get {
                return ResourceManager.GetString("IncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Type.
        /// </summary>
        internal static string IncomeType {
            get {
                return ResourceManager.GetString("IncomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        internal static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Capital.
        /// </summary>
        internal static string InitialCapital {
            get {
                return ResourceManager.GetString("InitialCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Investment.
        /// </summary>
        internal static string InitialInvestment {
            get {
                return ResourceManager.GetString("InitialInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment.
        /// </summary>
        internal static string Installment {
            get {
                return ResourceManager.GetString("Installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Number.
        /// </summary>
        internal static string InstallmentNumber {
            get {
                return ResourceManager.GetString("InstallmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Period.
        /// </summary>
        internal static string InstallmentPeriod {
            get {
                return ResourceManager.GetString("InstallmentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Date.
        /// </summary>
        internal static string IssuedDate {
            get {
                return ResourceManager.GetString("IssuedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Place.
        /// </summary>
        internal static string IssuedPlace {
            get {
                return ResourceManager.GetString("IssuedPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string JobPost {
            get {
                return ResourceManager.GetString("JobPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Status.
        /// </summary>
        internal static string JobStatus {
            get {
                return ResourceManager.GetString("JobStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judgmental Scoring.
        /// </summary>
        internal static string JudgmentalScoring {
            get {
                return ResourceManager.GetString("JudgmentalScoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Employment Duration.
        /// </summary>
        internal static string LastEmploymentDuration {
            get {
                return ResourceManager.GetString("LastEmploymentDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leased.
        /// </summary>
        internal static string Leased {
            get {
                return ResourceManager.GetString("Leased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lender.
        /// </summary>
        internal static string LenderOrg {
            get {
                return ResourceManager.GetString("LenderOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        internal static string Loan {
            get {
                return ResourceManager.GetString("Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Amount.
        /// </summary>
        internal static string LoanAmount {
            get {
                return ResourceManager.GetString("LoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Code.
        /// </summary>
        internal static string LoanCode {
            get {
                return ResourceManager.GetString("LoanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string LoanDepositType {
            get {
                return ResourceManager.GetString("LoanDepositType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string LoanEndDate {
            get {
                return ResourceManager.GetString("LoanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string LoanFromDate {
            get {
                return ResourceManager.GetString("LoanFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Info.
        /// </summary>
        internal static string LoanInfo {
            get {
                return ResourceManager.GetString("LoanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Major Type.
        /// </summary>
        internal static string LoanMajorType {
            get {
                return ResourceManager.GetString("LoanMajorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maturity Date.
        /// </summary>
        internal static string LoanMaturityDate {
            get {
                return ResourceManager.GetString("LoanMaturityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Reason.
        /// </summary>
        internal static string LoanReason {
            get {
                return ResourceManager.GetString("LoanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Records.
        /// </summary>
        internal static string LoanRecords {
            get {
                return ResourceManager.GetString("LoanRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate here your loans and other financial facilities.
        /// </summary>
        internal static string LoanRecordsTitle {
            get {
                return ResourceManager.GetString("LoanRecordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Status.
        /// </summary>
        internal static string LoanStatus {
            get {
                return ResourceManager.GetString("LoanStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Type.
        /// </summary>
        internal static string LoanType {
            get {
                return ResourceManager.GetString("LoanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Time.
        /// </summary>
        internal static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Activity.
        /// </summary>
        internal static string MainActivity {
            get {
                return ResourceManager.GetString("MainActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        internal static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        internal static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string MatchContains {
            get {
                return ResourceManager.GetString("MatchContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal to.
        /// </summary>
        internal static string MatchEqual {
            get {
                return ResourceManager.GetString("MatchEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        internal static string MatchStarts {
            get {
                return ResourceManager.GetString("MatchStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Case of Diseases Input Medical Expenses.
        /// </summary>
        internal static string MedicalExpenses {
            get {
                return ResourceManager.GetString("MedicalExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr.
        /// </summary>
        internal static string Mehr {
            get {
                return ResourceManager.GetString("Mehr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Type.
        /// </summary>
        internal static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Service.
        /// </summary>
        internal static string MilitaryService {
            get {
                return ResourceManager.GetString("MilitaryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining Scoring.
        /// </summary>
        internal static string MiningScoring {
            get {
                return ResourceManager.GetString("MiningScoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Income.
        /// </summary>
        internal static string MonthlyIncome {
            get {
                return ResourceManager.GetString("MonthlyIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MovableFixedAccountsRecordsTitle.
        /// </summary>
        internal static string MovableFixedAccountsRecordsTitle {
            get {
                return ResourceManager.GetString("MovableFixedAccountsRecordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movable and Fixed Assets.
        /// </summary>
        internal static string MovableFixedAssets {
            get {
                return ResourceManager.GetString("MovableFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate in the table your movable and fixed assets.
        /// </summary>
        internal static string MovableFixedAssetsTitle {
            get {
                return ResourceManager.GetString("MovableFixedAssetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rating result exists.
        /// </summary>
        internal static string MsgNoAssess {
            get {
                return ResourceManager.GetString("MsgNoAssess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        internal static string NationalID {
            get {
                return ResourceManager.GetString("NationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negin.
        /// </summary>
        internal static string Negin {
            get {
                return ResourceManager.GetString("Negin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Address.
        /// </summary>
        internal static string OfficeAddress {
            get {
                return ResourceManager.GetString("OfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Place.
        /// </summary>
        internal static string OfficeName {
            get {
                return ResourceManager.GetString("OfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Phone Number.
        /// </summary>
        internal static string OfficePhone {
            get {
                return ResourceManager.GetString("OfficePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Job Place.
        /// </summary>
        internal static string OfficeSecondName {
            get {
                return ResourceManager.GetString("OfficeSecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office2 Phone Number.
        /// </summary>
        internal static string OfficeSecondPhone {
            get {
                return ResourceManager.GetString("OfficeSecondPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Mortgage.
        /// </summary>
        internal static string OnMortgage {
            get {
                return ResourceManager.GetString("OnMortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnMortgage Amount.
        /// </summary>
        internal static string OnMortgageAmount {
            get {
                return ResourceManager.GetString("OnMortgageAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnMortgage Date.
        /// </summary>
        internal static string OnMortgageDate {
            get {
                return ResourceManager.GetString("OnMortgageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnMortgage Duration (in Year).
        /// </summary>
        internal static string OnMortgageDuration {
            get {
                return ResourceManager.GetString("OnMortgageDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership.
        /// </summary>
        internal static string Ownership {
            get {
                return ResourceManager.GetString("Ownership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Organisation.
        /// </summary>
        internal static string ParentOrganisation {
            get {
                return ResourceManager.GetString("ParentOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installement.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Number.
        /// </summary>
        internal static string PermitNumber {
            get {
                return ResourceManager.GetString("PermitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued By.
        /// </summary>
        internal static string PermitOrgIssued {
            get {
                return ResourceManager.GetString("PermitOrgIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permits.
        /// </summary>
        internal static string Permits {
            get {
                return ResourceManager.GetString("Permits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Edit the Information of a Permit Use Menus in the Footer.
        /// </summary>
        internal static string PermitsTitle {
            get {
                return ResourceManager.GetString("PermitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Type.
        /// </summary>
        internal static string PermitType {
            get {
                return ResourceManager.GetString("PermitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Number.
        /// </summary>
        internal static string PersonelNumber {
            get {
                return ResourceManager.GetString("PersonelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pledge Amount.
        /// </summary>
        internal static string PledgeAmount {
            get {
                return ResourceManager.GetString("PledgeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O Box.
        /// </summary>
        internal static string POBox {
            get {
                return ResourceManager.GetString("POBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction.
        /// </summary>
        internal static string Prediction {
            get {
                return ResourceManager.GetString("Prediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of Default.
        /// </summary>
        internal static string ProbabilityofDefault {
            get {
                return ResourceManager.GetString("ProbabilityofDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proprietary.
        /// </summary>
        internal static string proprietary {
            get {
                return ResourceManager.GetString("proprietary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        internal static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Record.
        /// </summary>
        internal static string RankingRecord {
            get {
                return ResourceManager.GetString("RankingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistrationPlace.
        /// </summary>
        internal static string RegistrationPlace {
            get {
                return ResourceManager.GetString("RegistrationPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemainingAmount.
        /// </summary>
        internal static string RemainingAmount {
            get {
                return ResourceManager.GetString("RemainingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Amount.
        /// </summary>
        internal static string RentAmount {
            get {
                return ResourceManager.GetString("RentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representation Number.
        /// </summary>
        internal static string RepresentationNumber {
            get {
                return ResourceManager.GetString("RepresentationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        internal static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Fields.
        /// </summary>
        internal static string ResetFields {
            get {
                return ResourceManager.GetString("ResetFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential Status.
        /// </summary>
        internal static string Resident {
            get {
                return ResourceManager.GetString("Resident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To score individuals add them to the table.
        /// </summary>
        internal static string RetailAssessMsg {
            get {
                return ResourceManager.GetString("RetailAssessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of data mining model used for scoring retail.
        /// </summary>
        internal static string RetailModelDM {
            get {
                return ResourceManager.GetString("RetailModelDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of judgmental model used for ranking retail.
        /// </summary>
        internal static string RetailModelJG {
            get {
                return ResourceManager.GetString("RetailModelJG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Approval.
        /// </summary>
        internal static string SaveApproval {
            get {
                return ResourceManager.GetString("SaveApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Phrase.
        /// </summary>
        internal static string SearchPhrase {
            get {
                return ResourceManager.GetString("SearchPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Holder.
        /// </summary>
        internal static string SearchPlace {
            get {
                return ResourceManager.GetString("SearchPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Job Information.
        /// </summary>
        internal static string SecondJobInformation {
            get {
                return ResourceManager.GetString("SecondJobInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        internal static string SelectDateMsg {
            get {
                return ResourceManager.GetString("SelectDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maturity Date.
        /// </summary>
        internal static string SelectMaturityDateMsg {
            get {
                return ResourceManager.GetString("SelectMaturityDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShareHolders.
        /// </summary>
        internal static string ShareHolders {
            get {
                return ResourceManager.GetString("ShareHolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares Percentage.
        /// </summary>
        internal static string SharesPercentage {
            get {
                return ResourceManager.GetString("SharesPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conjoint.
        /// </summary>
        internal static string SpouseInfo {
            get {
                return ResourceManager.GetString("SpouseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing Property (m2).
        /// </summary>
        internal static string StandingProperty {
            get {
                return ResourceManager.GetString("StandingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Code.
        /// </summary>
        internal static string StateCode {
            get {
                return ResourceManager.GetString("StateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        internal static string StateName {
            get {
                return ResourceManager.GetString("StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Entrance Date.
        /// </summary>
        internal static string StockEntranceDate {
            get {
                return ResourceManager.GetString("StockEntranceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offichial Journal.
        /// </summary>
        internal static string StrDocName1 {
            get {
                return ResourceManager.GetString("StrDocName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Balance.
        /// </summary>
        internal static string StrDocName2 {
            get {
                return ResourceManager.GetString("StrDocName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet.
        /// </summary>
        internal static string StrDocName3 {
            get {
                return ResourceManager.GetString("StrDocName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Statement.
        /// </summary>
        internal static string StrDocName4 {
            get {
                return ResourceManager.GetString("StrDocName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inaugural Document.
        /// </summary>
        internal static string StrDocName5 {
            get {
                return ResourceManager.GetString("StrDocName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShareHolders List.
        /// </summary>
        internal static string StrDocName6 {
            get {
                return ResourceManager.GetString("StrDocName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Loan Form.
        /// </summary>
        internal static string StrLoanRequest {
            get {
                return ResourceManager.GetString("StrLoanRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface (m2).
        /// </summary>
        internal static string Surface {
            get {
                return ResourceManager.GetString("Surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Deed.
        /// </summary>
        internal static string TitleDeed {
            get {
                return ResourceManager.GetString("TitleDeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximate Value of the Day for Machineries.
        /// </summary>
        internal static string ToolsMachinery {
            get {
                return ResourceManager.GetString("ToolsMachinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Data.
        /// </summary>
        internal static string TransferData {
            get {
                return ResourceManager.GetString("TransferData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity (In Month).
        /// </summary>
        internal static string Validity {
            get {
                return ResourceManager.GetString("Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Information.
        /// </summary>
        internal static string ViewInformation {
            get {
                return ResourceManager.GetString("ViewInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the names of the models for scoring.
        /// </summary>
        internal static string ViewModelNames {
            get {
                return ResourceManager.GetString("ViewModelNames", resourceCulture);
            }
        }
    }
}
