//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class localResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal localResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.localResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text About Credit Section in the Bank and evantually the software company.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Level.
        /// </summary>
        internal static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Security Required..
        /// </summary>
        internal static string AnswerRequired {
            get {
                return ResourceManager.GetString("AnswerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Security.
        /// </summary>
        internal static string AnswerSecurity {
            get {
                return ResourceManager.GetString("AnswerSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Role To Users.
        /// </summary>
        internal static string BTAssignRoles {
            get {
                return ResourceManager.GetString("BTAssignRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        internal static string BTCreateRole {
            get {
                return ResourceManager.GetString("BTCreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Users.
        /// </summary>
        internal static string BTDeleteUsers {
            get {
                return ResourceManager.GetString("BTDeleteUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassess.
        /// </summary>
        internal static string BTReassessText {
            get {
                return ResourceManager.GetString("BTReassessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Users from Role.
        /// </summary>
        internal static string BTRemoveRoles {
            get {
                return ResourceManager.GetString("BTRemoveRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string BTUploadText {
            get {
                return ResourceManager.GetString("BTUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string BUpload {
            get {
                return ResourceManager.GetString("BUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any scoring history .
        /// </summary>
        internal static string ChkFileMsg01 {
            get {
                return ResourceManager.GetString("ChkFileMsg01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of files already assessed :.
        /// </summary>
        internal static string ChkFileMsg02 {
            get {
                return ResourceManager.GetString("ChkFileMsg02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter a customer number.
        /// </summary>
        internal static string ChooseUser {
            get {
                return ResourceManager.GetString("ChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is required..
        /// </summary>
        internal static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Profile.
        /// </summary>
        internal static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer security is required.
        /// </summary>
        internal static string CUARMessage {
            get {
                return ResourceManager.GetString("CUARMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CUBCancelText {
            get {
                return ResourceManager.GetString("CUBCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string CUBFinish {
            get {
                return ResourceManager.GetString("CUBFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        internal static string CUBText {
            get {
                return ResourceManager.GetString("CUBText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully.
        /// </summary>
        internal static string CUCompleteSuccess {
            get {
                return ResourceManager.GetString("CUCompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string CUContinueButton {
            get {
                return ResourceManager.GetString("CUContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is duplicated.
        /// </summary>
        internal static string CUDEmailMessage {
            get {
                return ResourceManager.GetString("CUDEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string CUEmail {
            get {
                return ResourceManager.GetString("CUEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up your user account.
        /// </summary>
        internal static string CUHeader {
            get {
                return ResourceManager.GetString("CUHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for your new account.
        /// </summary>
        internal static string CUInstruction {
            get {
                return ResourceManager.GetString("CUInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Security.
        /// </summary>
        internal static string CULAnswer {
            get {
                return ResourceManager.GetString("CULAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Security.
        /// </summary>
        internal static string CULQuestion {
            get {
                return ResourceManager.GetString("CULQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question security is required.
        /// </summary>
        internal static string CUQRMessage {
            get {
                return ResourceManager.GetString("CUQRMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm the Delete operation?.
        /// </summary>
        internal static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have enough rights for this operation..
        /// </summary>
        internal static string DenyMessage {
            get {
                return ResourceManager.GetString("DenyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required..
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this information from the database?.
        /// </summary>
        internal static string EraseMsg {
            get {
                return ResourceManager.GetString("EraseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        internal static string GActionDesc {
            get {
                return ResourceManager.GetString("GActionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVName.
        /// </summary>
        internal static string GAVName {
            get {
                return ResourceManager.GetString("GAVName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Proceed.
        /// </summary>
        internal static string GDateAction {
            get {
                return ResourceManager.GetString("GDateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Type.
        /// </summary>
        internal static string GDetectType {
            get {
                return ResourceManager.GetString("GDetectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string GFileName {
            get {
                return ResourceManager.GetString("GFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malware.
        /// </summary>
        internal static string GMalwareName {
            get {
                return ResourceManager.GetString("GMalwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string GReport {
            get {
                return ResourceManager.GetString("GReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string GResult {
            get {
                return ResourceManager.GetString("GResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to view the report.
        /// </summary>
        internal static string GTOOLReport {
            get {
                return ResourceManager.GetString("GTOOLReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Last Result.
        /// </summary>
        internal static string HLViewResult {
            get {
                return ResourceManager.GetString("HLViewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save this information into the database? .
        /// </summary>
        internal static string InsertMsg {
            get {
                return ResourceManager.GetString("InsertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judgement System.
        /// </summary>
        internal static string JudgeAnalyze {
            get {
                return ResourceManager.GetString("JudgeAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judgmental scoring ..
        /// </summary>
        internal static string JudgmentMsg {
            get {
                return ResourceManager.GetString("JudgmentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Scoring.
        /// </summary>
        internal static string L1Default {
            get {
                return ResourceManager.GetString("L1Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Scoring is a powerful tool to decreases the risk in the Bank..
        /// </summary>
        internal static string L1_1Default {
            get {
                return ResourceManager.GetString("L1_1Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        internal static string L2Default {
            get {
                return ResourceManager.GetString("L2Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to assess your customers you have to login..
        /// </summary>
        internal static string L2_1Default {
            get {
                return ResourceManager.GetString("L2_1Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get more results.
        /// </summary>
        internal static string L3Default {
            get {
                return ResourceManager.GetString("L3Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Scoring software gives you the ability to score clients either through data mining algorithms or judgemental ones.
        /// </summary>
        internal static string L3_1Default {
            get {
                return ResourceManager.GetString("L3_1Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better solutions.
        /// </summary>
        internal static string L4Default {
            get {
                return ResourceManager.GetString("L4Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a Customer you can login and upload your documents and get faster response to your request.
        /// </summary>
        internal static string L4_1Default {
            get {
                return ResourceManager.GetString("L4_1Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string L5Default {
            get {
                return ResourceManager.GetString("L5Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string LAVName {
            get {
                return ResourceManager.GetString("LAVName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LBText {
            get {
                return ResourceManager.GetString("LBText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to search.
        /// </summary>
        internal static string LFileName {
            get {
                return ResourceManager.GetString("LFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string LLConfirmPass {
            get {
                return ResourceManager.GetString("LLConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string LLName {
            get {
                return ResourceManager.GetString("LLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LLPass {
            get {
                return ResourceManager.GetString("LLPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me next time.
        /// </summary>
        internal static string LLRemember {
            get {
                return ResourceManager.GetString("LLRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string LLTitle {
            get {
                return ResourceManager.GetString("LLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string LMsgWelcome {
            get {
                return ResourceManager.GetString("LMsgWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string MenuAdmin {
            get {
                return ResourceManager.GetString("MenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assess.
        /// </summary>
        internal static string MenuAssess {
            get {
                return ResourceManager.GetString("MenuAssess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clerk.
        /// </summary>
        internal static string MenuClerk {
            get {
                return ResourceManager.GetString("MenuClerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail .
        /// </summary>
        internal static string MenuMain1 {
            get {
                return ResourceManager.GetString("MenuMain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buisness.
        /// </summary>
        internal static string MenuMain2 {
            get {
                return ResourceManager.GetString("MenuMain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessments.
        /// </summary>
        internal static string MenuMain3 {
            get {
                return ResourceManager.GetString("MenuMain3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Data.
        /// </summary>
        internal static string MenuMain4 {
            get {
                return ResourceManager.GetString("MenuMain4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string MenuMain5 {
            get {
                return ResourceManager.GetString("MenuMain5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string MenuMain6 {
            get {
                return ResourceManager.GetString("MenuMain6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuMain7 {
            get {
                return ResourceManager.GetString("MenuMain7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string MenuRegister {
            get {
                return ResourceManager.GetString("MenuRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining scoring..
        /// </summary>
        internal static string MiningMsg {
            get {
                return ResourceManager.GetString("MiningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new record will be created..
        /// </summary>
        internal static string NewMsg {
            get {
                return ResourceManager.GetString("NewMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm the operation?.
        /// </summary>
        internal static string OperationMsg {
            get {
                return ResourceManager.GetString("OperationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password and Confirmation Password must match..
        /// </summary>
        internal static string PasswordCompare {
            get {
                return ResourceManager.GetString("PasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Continue Select a Corporate Record by Clicking on &quot;Select&quot; .
        /// </summary>
        internal static string PCorpSearchFooter {
            get {
                return ResourceManager.GetString("PCorpSearchFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Search Results.
        /// </summary>
        internal static string PCorpSearchHeader {
            get {
                return ResourceManager.GetString("PCorpSearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Page.
        /// </summary>
        internal static string PHeader {
            get {
                return ResourceManager.GetString("PHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clerk Page.
        /// </summary>
        internal static string PHeaderClerk {
            get {
                return ResourceManager.GetString("PHeaderClerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Data Entry.
        /// </summary>
        internal static string PHeaderData {
            get {
                return ResourceManager.GetString("PHeaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Report Page.
        /// </summary>
        internal static string PHeaderReport {
            get {
                return ResourceManager.GetString("PHeaderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Management .
        /// </summary>
        internal static string PHeaderRole {
            get {
                return ResourceManager.GetString("PHeaderRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management .
        /// </summary>
        internal static string PHeaderUser {
            get {
                return ResourceManager.GetString("PHeaderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Continue Select the Retail Record by Clicking on it.
        /// </summary>
        internal static string PRetailSearchFooter {
            get {
                return ResourceManager.GetString("PRetailSearchFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Search Results.
        /// </summary>
        internal static string PRetailSearchHeader {
            get {
                return ResourceManager.GetString("PRetailSearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alps Credit Scoring.
        /// </summary>
        internal static string ProgName {
            get {
                return ResourceManager.GetString("ProgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Security Required..
        /// </summary>
        internal static string QuestionRequired {
            get {
                return ResourceManager.GetString("QuestionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionSecurity.
        /// </summary>
        internal static string QuestionSecurity {
            get {
                return ResourceManager.GetString("QuestionSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        internal static string RegisterNew {
            get {
                return ResourceManager.GetString("RegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields will rest..
        /// </summary>
        internal static string ResetMsg {
            get {
                return ResourceManager.GetString("ResetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectGridText {
            get {
                return ResourceManager.GetString("SelectGridText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload status:.
        /// </summary>
        internal static string SMessageStatus {
            get {
                return ResourceManager.GetString("SMessageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of needed documents.
        /// </summary>
        internal static string SMsgDocs {
            get {
                return ResourceManager.GetString("SMsgDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload each document and then check the related document.
        /// </summary>
        internal static string SMsgDocs1 {
            get {
                return ResourceManager.GetString("SMsgDocs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register &amp; Send Document.
        /// </summary>
        internal static string SMsgDocs2 {
            get {
                return ResourceManager.GetString("SMsgDocs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string SMsgHello {
            get {
                return ResourceManager.GetString("SMsgHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can proceed to assess your file..
        /// </summary>
        internal static string SMsgMember1 {
            get {
                return ResourceManager.GetString("SMsgMember1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has been already analyzed. If you want to see the last analyze result.
        /// </summary>
        internal static string SMsgMember2 {
            get {
                return ResourceManager.GetString("SMsgMember2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Retail.
        /// </summary>
        internal static string SubMenu11 {
            get {
                return ResourceManager.GetString("SubMenu11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Retail.
        /// </summary>
        internal static string SubMenu12 {
            get {
                return ResourceManager.GetString("SubMenu12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Retail.
        /// </summary>
        internal static string SubMenu13 {
            get {
                return ResourceManager.GetString("SubMenu13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Scoring.
        /// </summary>
        internal static string SubMenu14 {
            get {
                return ResourceManager.GetString("SubMenu14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Retail Loan.
        /// </summary>
        internal static string SubMenu15 {
            get {
                return ResourceManager.GetString("SubMenu15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Buisness.
        /// </summary>
        internal static string SubMenu21 {
            get {
                return ResourceManager.GetString("SubMenu21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Buisness.
        /// </summary>
        internal static string SubMenu22 {
            get {
                return ResourceManager.GetString("SubMenu22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Buisness.
        /// </summary>
        internal static string SubMenu23 {
            get {
                return ResourceManager.GetString("SubMenu23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buisness Scoring.
        /// </summary>
        internal static string SubMenu24 {
            get {
                return ResourceManager.GetString("SubMenu24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Buisness Loan.
        /// </summary>
        internal static string SubMenu25 {
            get {
                return ResourceManager.GetString("SubMenu25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records of Scores.
        /// </summary>
        internal static string SubMenu31 {
            get {
                return ResourceManager.GetString("SubMenu31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed Scoring Forms.
        /// </summary>
        internal static string SubMenu32 {
            get {
                return ResourceManager.GetString("SubMenu32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Customers Data.
        /// </summary>
        internal static string SubMenu41 {
            get {
                return ResourceManager.GetString("SubMenu41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Assessment.
        /// </summary>
        internal static string SubMenu42 {
            get {
                return ResourceManager.GetString("SubMenu42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Report.
        /// </summary>
        internal static string SubMenu51 {
            get {
                return ResourceManager.GetString("SubMenu51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Report.
        /// </summary>
        internal static string SubMenu52 {
            get {
                return ResourceManager.GetString("SubMenu52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        internal static string SubMenu61 {
            get {
                return ResourceManager.GetString("SubMenu61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        internal static string SubMenu62 {
            get {
                return ResourceManager.GetString("SubMenu62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Management.
        /// </summary>
        internal static string SubMenu63 {
            get {
                return ResourceManager.GetString("SubMenu63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups Management.
        /// </summary>
        internal static string SubMenu64 {
            get {
                return ResourceManager.GetString("SubMenu64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string SubMenu65 {
            get {
                return ResourceManager.GetString("SubMenu65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Group.
        /// </summary>
        internal static string SubMenu66 {
            get {
                return ResourceManager.GetString("SubMenu66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string SubMenu67 {
            get {
                return ResourceManager.GetString("SubMenu67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Right.
        /// </summary>
        internal static string SubMenu68 {
            get {
                return ResourceManager.GetString("SubMenu68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is PD?.
        /// </summary>
        internal static string SubMenu69 {
            get {
                return ResourceManager.GetString("SubMenu69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Calculate PD.
        /// </summary>
        internal static string SubMenu70 {
            get {
                return ResourceManager.GetString("SubMenu70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string SWelcome {
            get {
                return ResourceManager.GetString("SWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation could take a moment depending to the network load..
        /// </summary>
        internal static string TakeTimeMsg {
            get {
                return ResourceManager.GetString("TakeTimeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTR.
        /// </summary>
        internal static string TextDirection {
            get {
                return ResourceManager.GetString("TextDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All information will be updated in the database..
        /// </summary>
        internal static string UpdateMsg {
            get {
                return ResourceManager.GetString("UpdateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        internal static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is required..
        /// </summary>
        internal static string UserRequired {
            get {
                return ResourceManager.GetString("UserRequired", resourceCulture);
            }
        }
    }
}
